### ISSUE TITLE
Spektrum stoped functioning in my Ubuntu 16.04 environment

### ISSUE THREAD

**Issue by satfan52** [pavels/spektrum#10]
Hello Pavel,

First many thanks for the application it actually provides a very nice entry ticket to the world of frequency response spectrum analysis. It is indeed very useful to get an indication of the fequency response of filters, antenna, etc...and other devices above 60Mhz where the red-pitaya (and your VNA application) can no longer help. 

a) My environment:
I am running Ubuntu 16.04 (latest version available to date - 17 December 2017) and I have installed Processing 3.3.6. I use the latest version of your app (1.0.2).

b) Background info about the way I use your app:
 To run your app in my environment,  I have to black-list the two modules
"dvb_usb_rtl2832u and "dvb_usb_rtl28xxu" in the file  /etc/modprobe.d/blacklist.conf. Without blacklisting these two modules, the app would just not start. As a side note, blacklisting the two modules, prevented GQRX to function so the choice for me was between using Spektrum or GQRX but the two apps could not be used at the same time (this is not the problem and is fine with me but it is important diagnosis info) 

c) The problem:
I have not used Spektrum for 1 or 2 months and I have tried to use it today to make some rf measurements. After blacklisting the two modules cited above to my great surprise the application did not start and I got the following error in terminal:

"Exception in thread "main" java.lang.NullPointerException
	at processing.core.PApplet.handleSettings(PApplet.java:957)
	at processing.core.PApplet.runSketch(PApplet.java:10234)
	at processing.core.PApplet.main(PApplet.java:10001)
	at spektrum.main(spektrum.java:510)"

I also noticed to my great suprise that GQRX was continuing to work with the two modules cited above disabled whereas in the past it would just stop working.

I checked with "lsmod" and blacklisting the two modules works. 

I have also checked if the error above was the same with two modules NOT black-listed (so loaded) and it is indeed the case. It looks like something has changed in the way Ubuntu works. 

Of course, I have also verified that Processing works and it seems ok to me.

d) My request:
I am looking for a work-around to be able to continue to use your software. I guess there must be some type of command I can use that would allow me to run your app.    

Regards
Peter/on7yi

**Comment by satfan52** [comment]
Problem solved by tuning permissions adequately
