### ISSUE TITLE
Device string on 2.0.1 causes a Java Error, app crashes when device is selected 

### ISSUE THREAD

**Issue by mesquitaandre** [pavels/spektrum#40]
The program can't get past the dropdown menu where you select the device. Once I click there, I get a java error. I believe it may have to do with the addition of the serial number to the device string in 2.0.1 It does not happen in 2.0.0, which works perfectly:

_[_mancha@mancha-pc spektrum]$ ./spektrum 
Loading libs from /home/mancha/SDR/spektrum/lib.
Library rtlsdr file /home/mancha/SDR/spektrum/lib/librtlsdr.so.
Library rtlpower file /home/mancha/SDR/spektrum/lib/librtlpower.so.
Generic RTL2832U OEM: 00000001
ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
Reached end of setup.
Loading libs from /home/mancha/SDR/spektrum/lib.
Library rtlsdr file /home/mancha/SDR/spektrum/lib/librtlsdr.so.
Library rtlpower file /home/mancha/SDR/spektrum/lib/librtlpower.so.
Found Rafael Micro R820T tuner
File config.csv
/home/mancha/SDR/spektrum/config.csv
File config.csv exists.
Reached end of makeconfig
Mar 31, 2021 10:01:53 PM controlP5.ControlBroadcaster printMethodError
SEVERE: An error occured while forwarding a Controller event, please check your code at deviceDropdown
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at controlP5.ControlBroadcaster.invokeMethod(Unknown Source)
        at controlP5.ControlBroadcaster.callTarget(Unknown Source)
        at controlP5.ControlBroadcaster.broadcast(Unknown Source)
        at controlP5.Controller.broadcast(Unknown Source)
        at controlP5.Controller.setValue(Unknown Source)
        at controlP5.ListBox.onRelease(Unknown Source)
        at controlP5.Controller.setMousePressed(Unknown Source)
        at controlP5.ControllerGroup.setMousePressed(Unknown Source)
        at controlP5.ControlWindow.mouseReleasedEvent(Unknown Source)
        at controlP5.ControlWindow.mouseEvent(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1436)
        at processing.core.PApplet.handleMethods(PApplet.java:1638)
        at processing.core.PApplet.handleMouseEvent(PApplet.java:2749)
        at processing.core.PApplet.dequeueEvents(PApplet.java:2652)
        at processing.core.PApplet.handleDraw(PApplet.java:2493)
        at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
        at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:313)
Caused by: java.lang.IllegalArgumentException: This table has no column named 'minFreq'
        at processing.data.Table.getColumnIndex(Table.java:2228)
        at processing.data.Table.getColumnIndex(Table.java:2198)
        at processing.data.Table.getInt(Table.java:3079)
        at spektrum.loadConfig(spektrum.java:1932)
        at spektrum.deviceDropdown(spektrum.java:1398)
        ... 24 more
deviceDropdown__
![LongName](https://user-images.githubusercontent.com/81688776/113140191-9abc7800-926f-11eb-88dd-f42f474871c6.png)

**Comment by pavels** [comment]
This looks like corrupted config file, try to delete and start over

Reopen if needed
